name: chat_journal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  image_picker: ^0.8.6
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_slidable: ^2.0.0
  sqflite:
  path:
  shared_preferences: ^2.0.17
  firebase_core: ^2.8.0
  firebase_database: ^10.0.10
  firebase_auth: any
  mockito: ^5.3.2
  build_runner: ^2.3.3
  firebase_storage: ^11.0.11
  cached_network_image: ^3.2.3
  path_provider: ^2.0.12
  local_auth: ^2.1.3
  share_plus: ^6.3.1
  hashtager: ^1.0.4
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  firebase_storage_mocks: ^0.6.1
  firebase_database_mocks: ^0.6.0
  firebase_auth_mocks: ^0.11.0
  bloc_test: ^9.1.1
  syncfusion_flutter_charts: any


provider:
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.20.0
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
  generate: true